### PR TITLE
Add testcases for various housenumber types

### PR DESCRIPTION
**Pull request by hbruch**
Add some testcases for housenumbers with various suffixes, case variations, hyphenation etc.

### CODE REVIEW

**Comment by nlehuby** [comment]
@yohanboniface do you want to review this PR? Otherwise, I'll merge it.

**Comment by hbruch** [comment]
I just noticed I need to provide lang=de, so geocoder instances defaulting to english would return 'Hannover' instead of 'Hannover'.

**Comment by hbruch** [comment]
Another question: are there any conventions for the names of subfolders, e.g. modelling the osm admin-level hierarchy? Probably I should then rename the folder to niedersachsen?

**Comment by yohanboniface** [comment]
> Another question: are there any conventions for the names of subfolders, e.g. modelling the osm admin-level hierarchy? Probably I should then rename the folder to niedersachsen?

There is no convention at this level. The constraint is that every subfolder is automatically transformed as a tag (so it can be used as filters when running py.test) so for example it should not contain dashes (otherwise they are parsed as "minus" by pytest).
As you have certainly noticed, he usage is to have geographical subfolders, and inside them optional "typed" subfolders.
I think we need to be consistent for the "typed" subfolders (given they are used several times), but geographical subfolders are fine as soon as people interested in this area understand its name.

**Pull request merged**
